name       : materia-kde
version    : '20180904'
release    : 2
source     :
    - https://github.com/PapirusDevelopmentTeam/materia-kde/archive/20180904.tar.gz : c3460b11826f20e79532a4649bb785db729afbb1b0981aa972c30661461d9b7e
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Materia KDE customization
rundeps    :
    - kvantum
description: |
    This is a port of the popular GTK theme Materia for Plasma 5 desktop with a few additions and extras.
install    : |
    %make_install
