name       : materia-kde
version    : '20190319'
release    : 3
source     :
    - https://github.com/PapirusDevelopmentTeam/materia-kde/archive/20190319.tar.gz : 9a6c0a6294392aff8f39f529675be54f9d4c7bcefed162984af09b60a3625fdf
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Materia KDE customization
rundeps    :
    - kvantum
description: |
    This is a port of the popular GTK theme Materia for Plasma 5 desktop with a few additions and extras.
install    : |
    %make_install
