name       : materia-kde
version    : '20190506'
release    : 4
source     :
    - https://github.com/PapirusDevelopmentTeam/materia-kde/archive/20190506.tar.gz : 51b26f0dd7eb6a0bd44cef0309c200ecbf0e1c34cc3b5ca7ba1ad1dad06ec9be
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Materia KDE customization
rundeps    :
    - kvantum
description: |
    This is a port of the popular GTK theme Materia for Plasma 5 desktop with a few additions and extras.
install    : |
    %make_install
